breadcrumb_separator:
  type: string
  default: " › "
  description: "The separator to use between category levels in the breadcrumb trail."

breadcrumb_styles:
  type: string
  default: ""
  description: "Additional CSS to style the parent categories in the breadcrumb trail. Example: font-style: italic;"

hide_on_mobile:
  type: bool
  default: true
  description: "Hide parent categories on mobile devices to save space."

max_breadcrumb_depth:
  type: integer
  default: 3
  description: "Maximum number of category levels to show in the breadcrumb (0 = no limit)."